# Generated by Django 5.0.1 on 2024-03-26 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunePath',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RuneSlot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('slot_number', models.IntegerField()),
                ('rune_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.runepath')),
            ],
        ),
    ]
