# Generated by Django 5.0.1 on 2024-03-19 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('colloq', models.CharField(blank=True, max_length=255)),
                ('plaintext', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='item_images/')),
                ('gold_base', models.IntegerField()),
                ('gold_total', models.IntegerField()),
                ('gold_sell', models.IntegerField()),
                ('item_from', models.ManyToManyField(blank=True, related_name='crafts_into', to='items.item')),
                ('item_into', models.ManyToManyField(blank=True, related_name='crafts_from', to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.stat')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='stats',
            field=models.ManyToManyField(through='items.ItemStat', to='items.stat'),
        ),
    ]
