# Generated by Django 5.0.1 on 2024-03-15 09:07

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('colloq', models.CharField(max_length=255)),
                ('plaintext', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=15)),
                ('gold_base', models.IntegerField()),
                ('gold_total', models.IntegerField()),
                ('gold_sell', models.IntegerField()),
                ('item_from', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('item_into', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.stat')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='stats',
            field=models.ManyToManyField(through='items.ItemStat', to='items.stat'),
        ),
    ]
