# Generated by Django 5.0.1 on 2024-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_tag_alter_item_image_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='identification',
            field=models.IntegerField(unique=True),
        ),
    ]
